#!/usr/bin/env python3
"""Generate portable notices for every external package in the GPU Cargo.lock.

Uses Cargo's registry source plus exact upstream revisions for crates that omit
license files. No platform filter: Linux, Metal and other resolved target deps
are included. Does not choose or create a project-wide license for Voxy.
"""
import argparse
import hashlib
import json
import os
import pathlib
import shutil
import subprocess
import tempfile
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
MARKER = '.generated-gpu-licenses'

def sha(data):
    return hashlib.sha256(data).hexdigest()

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=pathlib.Path, default=ROOT/'packaging/gpu-licenses')
    args = parser.parse_args()
    output = args.output.resolve()
    if output.exists() and not (output/MARKER).is_file():
        raise SystemExit('Refusing to replace a directory not generated by this script')
    metadata = json.loads(subprocess.check_output([
        os.environ.get('CARGO', 'cargo'), 'metadata', '--locked', '--format-version', '1',
        '--manifest-path', str(ROOT/'gpu/Cargo.toml'),
    ]))
    packages = sorted((p for p in metadata['packages'] if p['source']), key=lambda p:(p['name'],p['version']))
    output.parent.mkdir(parents=True, exist_ok=True)
    stage = pathlib.Path(tempfile.mkdtemp(prefix='.gpu-licenses-', dir=output.parent))
    fetched = {}
    try:
        (stage/MARKER).write_text('Generated by scripts/generate-gpu-licenses.py; replace as a unit.\n')
        common = stage/'common'; common.mkdir()
        wgpu = next(p for p in packages if p['name']=='wgpu')
        apache = pathlib.Path(wgpu['manifest_path']).parent/'LICENSE.APACHE'
        if not apache.exists():
            raise RuntimeError('Pinned wgpu Apache license file is missing')
        shutil.copyfile(apache, common/'Apache-2.0.txt')
        index=[]
        for package in packages:
            name, version = package['name'], package['version']
            source = pathlib.Path(package['manifest_path']).parent
            destination = stage/'crates'/(name+'-'+version)
            destination.mkdir(parents=True)
            notices=[]
            vcs_path = source/'.cargo_vcs_info.json'
            vcs = json.loads(vcs_path.read_text()) if vcs_path.is_file() else {}
            revision = vcs.get('git',{}).get('sha1')
            repository = package.get('repository')
            candidates = {p for p in source.rglob('*') if p.is_file() and p.name.upper().startswith(('LICENSE','COPYING','NOTICE','COPYRIGHT'))}
            if package.get('license_file'):
                candidate = source/package['license_file']
                if candidate.is_file():candidates.add(candidate)
            for path in sorted(candidates):
                relative = path.relative_to(source)
                target = destination/relative
                target.parent.mkdir(parents=True,exist_ok=True)
                data=path.read_bytes();target.write_bytes(data)
                notices.append({'file':str(target.relative_to(stage)), 'origin':'published crate: '+str(relative), 'sha256':sha(data)})
            if not notices:
                # Only known, explicitly audited upstream fallbacks are allowed.
                mapping = {
                    'https://github.com/madsmtm/objc2': 'LICENSE.md',
                    'https://github.com/aclysma/profiling': 'LICENSE-APACHE',
                    'https://github.com/gfx-rs/rspirv': 'LICENSE',
                }
                if repository in mapping and revision:
                    filename=mapping[repository]
                    url='https://raw.githubusercontent.com/'+repository.removeprefix('https://github.com/')+'/'+revision+'/'+filename
                    if url not in fetched:
                        with urllib.request.urlopen(url,timeout=30) as response:
                            fetched[url]=response.read(1024*1024)
                    data=fetched[url]
                    if not data or len(data)>=1024*1024:raise RuntimeError('Invalid upstream notice size')
                    target=destination/filename;target.write_bytes(data)
                    notices.append({'file':str(target.relative_to(stage)),'origin':url,'sha256':sha(data)})
                elif repository=='https://github.com/r-efi/r-efi' and revision and 'Apache-2.0' in (package.get('license') or ''):
                    # This release carries its declaration in README and AUTHORS,
                    # with Apache-2.0 as one permitted alternative.
                    for filename in ('README.md','AUTHORS'):
                        data=(source/filename).read_bytes();target=destination/filename;target.write_bytes(data)
                        notices.append({'file':str(target.relative_to(stage)), 'origin':repository+'/blob/'+revision+'/'+filename, 'sha256':sha(data)})
                    notices.append({'file':'common/Apache-2.0.txt','origin':'Apache-2.0 alternative declared by this crate','sha256':sha(apache.read_bytes())})
                else:
                    raise RuntimeError('No audited license notice source for '+name+' '+version)
            index.append({'name':name,'version':version,'spdx':package.get('license'),'repository':repository,'revision':revision,'notices':notices})
        lock_hash=sha((ROOT/'gpu/Cargo.lock').read_bytes())
        (stage/'index.json').write_text(json.dumps({'cargo_lock_sha256':lock_hash,'scope':'All external packages resolved by gpu/Cargo.lock, without platform filtering','packages':index},indent=2,sort_keys=True)+'\n')
        (stage/'README.txt').write_text('Third-party notices for the Voxy/Nopal GPU worker\n\n'
            'This directory covers all external packages resolved by gpu/Cargo.lock,\n'
            'including Linux Vulkan and macOS Metal dependencies. Some entries are\n'
            'build-only or belong to other targets; inclusion is intentionally broad.\n'
            'index.json identifies each exact package, SPDX declaration, repository,\n'
            'revision when available, notice origin and SHA256. Crate-provided notices\n'
            'are copied verbatim. Missing crate files are retrieved from pinned\n'
            'upstream revisions; r-efi includes its README/AUTHORS and common Apache2.\n'
            'This collection does not establish a project-wide license for Voxy.\n\n'
            'Regenerate: python3 scripts/generate-gpu-licenses.py\n'
            'Requires Cargo, Python3 and network access for registry/pinned sources.\n')
        paths=sorted(p for p in stage.rglob('*') if p.is_file())
        (stage/'SHA256SUMS').write_text(''.join(sha(p.read_bytes())+'  '+str(p.relative_to(stage))+'\n' for p in paths))
        for directory,_,files in os.walk(stage):
            os.chmod(directory,0o755)
            for filename in files:os.chmod(pathlib.Path(directory)/filename,0o644)
        if output.exists():shutil.rmtree(output)
        stage.rename(output)
        print(json.dumps({'output':str(output),'packages':len(index),'notices':sum(len(p['notices']) for p in index),'cargo_lock_sha256':lock_hash}))
    finally:
        if stage.exists():shutil.rmtree(stage)

if __name__=='__main__':
    main()
